# VSCode Extensions

| Plugins                                                                                                               | Description                                                                                                     |
| --------------------------------------------------------------------------------------------------------------------- | --------------------------------------------------------------------------------------------------------------- |
| [:emojisense:](https://marketplace.visualstudio.com/items?itemName=bierner.emojisense)                                | Adds suggestions and autocomplete for emoji                                                                     |
| [Astro](https://marketplace.visualstudio.com/items?itemName=bierner.emojisense)                                       | Language support for Astro                                                                                      |
| [Auto Rename Tag](https://marketplace.visualstudio.com/items?itemName=formulahendry.auto-rename-tag)                  | Auto rename paired HTML/XML tag                                                                                 |
| [Awesome Flutter Snippets](https://marketplace.visualstudio.com/items?itemName=Nash.awesome-flutter-snippets)         | Awesome Flutter Snippets is a collection snippets and shortcuts for commonly used Flutter functions and classes |
| [Bracket Pair Colorizer](https://marketplace.visualstudio.com/items?itemName=CoenraadS.bracket-pair-colorizer)        | colorizing matching brackets, customizable. Really useful for code readbility                                   |
| [Dracula Theme](https://marketplace.visualstudio.com/items?itemName=dracula-theme.theme-dracula)                      | My favorite theme                                                                                               |
| [ES7 React Snippets](https://marketplace.visualstudio.com/items?itemName=dsznajder.es7-react-js-snippets)             | Simple extensions for React, Redux and Graphql in JS/TS with ES7 syntax                                         |
| [Git Graph](https://marketplace.visualstudio.com/items?itemName=mhutchie.git-graph)                                   | View a Git Graph of your repository, and perform Git actions from the graph.                                    |
| [Indent-Rainbow](https://marketplace.visualstudio.com/items?itemName=oderwat.indent-rainbow)                          | Makes indentation easier to read                                                                                |
| [Ionic Snippets](https://marketplace.visualstudio.com/items?itemName=fivethree.vscode-ionic-snippets)                 | Ionic snippets for VS Code                                                                                      |
| [Markdown Preview](https://marketplace.visualstudio.com/items?itemName=shd101wyy.markdown-preview-enhanced)           | Markdown Preview Enhanced ported to vscode                                                                      |
| [Material Theme Icons](https://marketplace.visualstudio.com/items?itemName=PKief.material-icon-theme)                 | Material Design Icons for Visual Studio Code                                                                    |
| [MDX](https://marketplace.visualstudio.com/items?itemName=silvenon.mdx)                                               | Provides syntax highlighting and bracket matching for MDX (JSX in Markdown) files.                              |
| [Prettier](https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode)                                | Code formatter using prettier                                                                                   |
| [SnipSnap](https://marketplace.visualstudio.com/items?itemName=snipsnapdev.snipsnap-vscode)                           | Code snippets for React, Gatsby, Next.js, Redux and more                                                        |
| [Svelte](https://marketplace.visualstudio.com/items?itemName=svelte.svelte-vscode)                                    | Svelte language support for VS Code                                                                             |
| [TailwindCSS Intellisense](https://marketplace.visualstudio.com/items?itemName=bradlc.vscode-tailwindcss)             | Intelligent Tailwind CSS tooling for VS Code                                                                    |
| [vscode-icons](https://marketplace.visualstudio.com/items?itemName=vscode-icons-team.vscode-icons)                    | another icons theme for VS Code                                                                                 |
| [VSCode Conventional Commits](https://marketplace.visualstudio.com/items?itemName=vivaxy.vscode-conventional-commits) | Conventional Commits for VSCode.                                                                                |

[⬆️ Back to Categories](/bookmarks)
